import "./globals.css";
import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import LoadingWrapper from "@/components/defined-ui/loadingWrapper";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className={spaceGrotesk.className}>
          <LoadingWrapper>{children}</LoadingWrapper>
        </div>
      </body>
    </html>
  );
}
